create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "first_name" text,
    "last_name" text,
    "email" text,
    "is_premium" boolean default false,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";



